# Generated by Django 3.0.5 on 2020-10-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=1000, verbose_name='confirmation code'),
        ),
    ]
