# Generated by Django 3.0.5 on 2020-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
